### PR TITLE
Fix Marshallable's fromCC

### PR DESCRIPTION
**Pull request by jtarvydas**
This brings back a fix that was removed in 3.3.4.7 to avoid compiler warnings when a property value's type cannot be null.

Since updating to 3.3.4.7, we've also been seeing dead code errors after calls to the DSL's select step. This PR also addresses this issue. Unfortunately, I have not yet been able to get a simple reproducible example together to contribute to DSLSpec, however it would appear to also be related to the fix for #265.  Fundamentally, the problem in #265 occurs when fromCCParams is empty. When the empty fromCCParams gets spliced into immutable.List.apply, the type of the resulting List is `List[Nothing]` (hence the _2 is not a member of Nothing errors).  Explicitly providing a type parameter to List fixes the issues.

### CODE REVIEW

**Comment by mpollmeier** [comment]
Ah, declaring the list type is a nicer way of handling those edge cases. Thanks!
I hope my future self will remember not to change this back, so if you happen to find a way to test this, that would make sure it stays that way :)
