### ISSUE TITLE
Example under "Mapping vertices from/to case classes" does not compile

### ISSUE THREAD

**Issue by jec** [mpollmeier/gremlin-scala#239]
I've created this `Main.scala`:

```scala
import gremlin.scala.{id, label}

@label("example")
case class Example(@id id: Option[Int],
                  longValue: Long,
                  stringValue: Option[String])

object Main extends App {
 import gremlin.scala._
 import org.apache.tinkerpop.gremlin.tinkergraph.structure.TinkerGraph

 implicit val graph = TinkerGraph.open.asScala
 val example = Example(None, Long.MaxValue, Some("optional value"))
 val v: Vertex = graph + example
 val v1: Example = v.toCC[Example] // equal to `example`, but with id set
}
```

`sbt run` responds with:

```
[error] src/test-gremlin-scala/src/main/scala/Main.scala:14:24: could not find implicit value for evidence parameter of type gremlin.scala.Marshallable[Example]
[error]  val v: Vertex = graph + example
[error]                        ^
[error] src/test-gremlin-scala/src/main/scala/Main.scala:15:26: could not find implicit value for evidence parameter of type gremlin.scala.Marshallable[Example]
[error]  val v1: Example = v.toCC[Example] // equal to `example`, but with id set
[error]                          ^
[error] two errors found
[error] (Compile / compileIncremental) Compilation failed
```

Is the example missing an `import` or not setting an `implicit val`?

**Comment by jec** [comment]
After perusing `MarshallableSpec`, I realized I indeed was missing an `implcit val` of type `Marshallable[Example]`.

**Comment by mpollmeier** [comment]
When I paste your exact code into a file it compiles fine, the implicit `Marshallable[Example]` is automatically generated with a macro. Did you end up writing it manually? The whole point is that you don't need to do that...

**Comment by jec** [comment]
I was never able to get the macros to work correctly, so I wrote the marshaller myself.

**Comment by jec** [comment]
Actually I just revisited this and tried something on a whim. My above errors are with Scala 2.12.5. I updated `build.sbt` to use 2.12.4, and it works.

**Comment by jec** [comment]
I can confirm that this example does compile in 2.12.6.
